<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>AvaloniaEx.Controls</RootNamespace>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	</PropertyGroup>

	<ItemGroup>
	  <AvaloniaXaml Remove="LookupEdit.axaml" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Assets\Images\alert.png" />
	  <None Remove="Assets\Images\question.png" />
	  <None Remove="Assets\Images\stop.png" />
	  <None Remove="Assets\Images\warning.png" />
	</ItemGroup>

	<ItemGroup>
	  <AvaloniaResource Include="Assets\Images\alert.png" />
	  <AvaloniaResource Include="Assets\Images\question.png" />
	  <AvaloniaResource Include="Assets\Images\stop.png" />
	  <AvaloniaResource Include="Assets\Images\warning.png" />
	</ItemGroup>

	<ItemGroup>
	  <PackageReference Include="Avalonia" Version="12.0.1" />
	  <PackageReference Include="System.Reactive" Version="6.1.0" />
	</ItemGroup>
</Project>
